### ISSUE TITLE
An issue after installing requirements

### ISSUE THREAD

**Issue by egorsmkv** [proger/haloop#2]
```
root@haloopt2:~/haloop# python3 -m ha.loop.main
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.0.4) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/root/haloop/ha/loop.py", line 15, in <module>
    from .init import create_model
  File "/root/haloop/ha/init.py", line 12, in <module>
    from .attention import GPT
  File "/root/haloop/ha/attention.py", line 115, in <module>
    from flash_attn.modules.mha import MHA
ModuleNotFoundError: No module named 'flash_attn'
```

**Comment by egorsmkv** [comment]
Am I right that I need to install it like the following: `pip install flash-attn==1.0.9`?

**Comment by proger** [comment]
Yeah the code in the `rope` branch needs flash-attn 1.0.9 and [its rotary extension](https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary). I'll be adding these dependencies when I'm ready to merge that branch. 

If you're training LSTM models you can comment out attention imports in ha.init: https://github.com/proger/haloop/blob/7674091082704e4662c30133843a9d1ec14f6e22/ha/init.py#L12-L13

**Comment by egorsmkv** [comment]
It would be convenient if these attention imports can be disabled, because flash-attn library requires nvcc binary which is hard to install on some systems.

**Comment by proger** [comment]
Latest code uses torch.nn.functional.scaled_dot_product_attention for simplicity
